#! python3
#This program is a a phone number and email extractor
import pyperclip, re
#Phone number regex
phoneNumRegex = re.compile(r'''(
    (\d{3}|\(\d{3}\))?   #Area Code
    (\s|-|\.)?    #Seperator
    (\d{3})     #First Three
    (\s|r'-'|\.)     #Seperator
    (\d{4})     #First Three
    (\s*(ext|x|ext.)\s*(\d{2,5}))?  #Extension
    )''', re.VERBOSE)
#Email regex
emailRegex = re.compile(r'''(
    [a-zA-Z0-9.%_+-]+ #username
    @ #@ symbol
    [a-zA-Z0-9.-]+ #domain
    (\.[a-zA-Z]{2,4}) # .something
    )''', re.VERBOSE)
#Copy clipboard and find matches
text = str(pyperclip.paste())
matches = []
for groups in phoneNumRegex.findall(text):
    newNumber = '-'.join([groups[1],groups[3],groups[5]])
    if groups[8] != '':
        newNumber += ' x' + groups[8]
    matches.append(newNumber)
for groups in emailRegex.findall(text):
    matches.append(groups[0])
#Return formatted matches or no matches found
if len(matches) > 0:
    pyperclip.copy('\n'.join(matches))
    print("Copied to clipboard")
    print('\n'.join(matches))
else:
    print('No matches on phone numbers or emails found')

